title: Modular Web Framework (MWF)
description: The Modular Web Framework (MWF) allows you to create modular web applications with the .NET framework.
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: true

url: https://rcl-modular-web-framework.github.io

aux_links:
  Template Repository: https://github.com/rcl-modular-web-framework/docs